name: Scales

settings:
    - ArgRequiredElseHelp

args: []

subcommands:
    - install:
        about: "Installs dependencies from the scalesfile"
    - add:
        about: "Adds a dependency to the scalesfile"
        args:
          - packages:
              about: "Packages to install"
              multiple_values: true
              required: true
    - remove:
        about: "Removes a dependency from the scalesfile"
        args:
          - packages:
              about: "Packages to remove"
              multiple_values: true
              required: true
    - show:
        about: "Shows information from your scalesfile"
    - init:
        about: "Creates a new scales project from the current dir"
        args:
          - name:
              about: "Name of package"
          - version:
              about: "Version of the package you are creating"
          - force:
              about: "Create a project even if one exists in current/parent dirs"
              takes_value: false
              long: "force"
              short: "F"
